dh_auditor:
  enabled: true
  providers:
    doctrine:
#      entities:
#        App\Entity\Author: ~
      viewer: true
      table_prefix: ~
      table_suffix: '_audit'
#      storage_mapper: App\Service\MyStorageMapper::map
      storage_services:
        - '@doctrine.orm.default_entity_manager'
#        - '@doctrine.orm.audits_entity_manager'