doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_sqlite'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
#                schema_filter: ~^.+(?<!_audit)$~  # audit tables are suffixed with "_audit" by default
            audits:
                # configure these for your database server
                driver: 'pdo_sqlite'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:AUDITS_DATABASE_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            audits:
                connection: audits
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
